export const PETITION_LINKS = {
  Alabama: "www.change.org/ameelioconnect-alabama",
  Alaska: "www.change.org/ameelioconnect-alaska",
  Arizona: "www.change.org/ameelioconnect-arizona",
  Arkansas: "www.change.org/ameelioconnect-arkansas",
  California: "www.change.org/ameelioconnect-california",
  Delaware: "www.change.org/ameelioconnect-delaware",
  Florida: "www.change.org/ameelioconnect-florida",
  Georgia: "www.change.org/ameelioconnect-georgia",
  Hawaii: "www.change.org/ameelioconnect-hawaii",
  Idaho: "www.change.org/ameelioconnect-idaho",
  Illinois: "www.change.org/ameelioconnect-illinois",
  Indiana: "www.change.org/ameelioconnect-indiana",
  Kansas: "www.change.org/ameelioconnect-kansas",
  Kentucky: "www.change.org/ameelioconnect-kentucky",
  Louisiana: "www.change.org/ameelioconnect-louisiana",
  Maine: "www.change.org/ameelioconnect-maine",
  Maryland: "www.change.org/ameelioconnect-maryland",
  Massachusetts: "www.change.org/ameelioconnect-massachusetts",
  Michigan: "www.change.org/ameelioconnect-michigan",
  Minnesota: "www.change.org/ameelioconnect-minnesota",
  Mississippi: "www.change.org/ameelioconnect-mississippi",
  Missouri: "www.change.org/ameelioconnect-missouri",
  Montana: "www.change.org/ameelioconnect-montana",
  Nebraska: "www.change.org/ameelioconnect-nebraska",
  Nevada: "www.change.org/ameelioconnect-nevada",
  "New Hampshire": "www.change.org/ameelioconnect-newhampshire",
  "New Jersey": "www.change.org/ameelioconnect-newjersey",
  "New Mexico": "www.change.org/ameelioconnect-newmexico",
  "New York": "www.change.org/ameelioconnect-newyork",
  "North Carolina": "www.change.org/ameelioconnect-northcarolina",
  "North Dakota": "www.change.org/ameelioconnect-northdakota",
  Ohio: "www.change.org/ameelioconnect-ohio",
  Oklahoma: "www.change.org/ameelioconnect-oklahoma",
  Oregon: "www.change.org/ameelioconnect-oregon",
  Pennsylvania: "www.change.org/ameelioconnect-pennsylvania",
  "Rhode Island": "www.change.org/ameelioconnect-rhodeisland",
  "South Carolina": "www.change.org/ameelioconnect-southcarolina",
  "South Dakota": "www.change.org/ameelioconnect-southdakota",
  Tennessee: "www.change.org/ameelioconnect-tennessee",
  Texas: "www.change.org/ameelioconnect-texas",
  Utah: "www.change.org/ameelioconnect-utah",
  Vermont: "www.change.org/ameelioconnect-vermont",
  Virginia: "www.change.org/ameelioconnect-virginia",
  "Washington State": "www.change.org/ameelioconnect-washingtonstate",
  "West Virginia": "www.change.org/ameelioconnect-westvirginia",
  Wisconsin: "www.change.org/ameelioconnect-wisconsin",
  Wyoming: "www.change.org/ameelioconnect-wyoming",
  Federal: "www.change.org/ameelioconnect",
};
