import { US_STATE } from ".";

export const PETITION_LINKS: Record<US_STATE, string> = {
  Alabama: "https://www.change.org/ameelioconnect-alabama",
  Alaska: "https://www.change.org/ameelioconnect-alaska",
  Arizona: "https://www.change.org/ameelioconnect-arizona",
  Arkansas: "https://www.change.org/ameelioconnect-arkansas",
  California: "https://www.change.org/ameelioconnect-california",
  Delaware: "https://www.change.org/ameelioconnect-delaware",
  Florida: "https://www.change.org/ameelioconnect-florida",
  Georgia: "https://www.change.org/ameelioconnect-georgia",
  Hawaii: "https://www.change.org/ameelioconnect-hawaii",
  Idaho: "https://www.change.org/ameelioconnect-idaho",
  Illinois: "https://www.change.org/ameelioconnect-illinois",
  Indiana: "https://www.change.org/ameelioconnect-indiana",
  Kansas: "https://www.change.org/ameelioconnect-kansas",
  Kentucky: "https://www.change.org/ameelioconnect-kentucky",
  Louisiana: "https://www.change.org/ameelioconnect-louisiana",
  Maine: "https://www.change.org/ameelioconnect-maine",
  Maryland: "https://www.change.org/ameelioconnect-maryland",
  Massachusetts: "https://www.change.org/ameelioconnect-massachusetts",
  Michigan: "https://www.change.org/ameelioconnect-michigan",
  Minnesota: "https://www.change.org/ameelioconnect-minnesota",
  Mississippi: "https://www.change.org/ameelioconnect-mississippi",
  Missouri: "https://www.change.org/ameelioconnect-missouri",
  Montana: "https://www.change.org/ameelioconnect-montana",
  Nebraska: "https://www.change.org/ameelioconnect-nebraska",
  Nevada: "https://www.change.org/ameelioconnect-nevada",
  "New Hampshire": "https://www.change.org/ameelioconnect-newhampshire",
  "New Jersey": "https://www.change.org/ameelioconnect-newjersey",
  "New Mexico": "https://www.change.org/ameelioconnect-newmexico",
  "New York": "https://www.change.org/ameelioconnect-newyork",
  "North Carolina": "https://www.change.org/ameelioconnect-northcarolina",
  "North Dakota": "https://www.change.org/ameelioconnect-northdakota",
  Ohio: "https://www.change.org/ameelioconnect-ohio",
  Oklahoma: "https://www.change.org/ameelioconnect-oklahoma",
  Oregon: "https://www.change.org/ameelioconnect-oregon",
  Pennsylvania: "https://www.change.org/ameelioconnect-pennsylvania",
  "Rhode Island": "https://www.change.org/ameelioconnect-rhodeisland",
  "South Carolina": "https://www.change.org/ameelioconnect-southcarolina",
  "South Dakota": "https://www.change.org/ameelioconnect-southdakota",
  Tennessee: "https://www.change.org/ameelioconnect-tennessee",
  Texas: "https://www.change.org/ameelioconnect-texas",
  Utah: "https://www.change.org/ameelioconnect-utah",
  Vermont: "https://www.change.org/ameelioconnect-vermont",
  Virginia: "https://www.change.org/ameelioconnect-virginia",
  "Washington": "https://www.change.org/ameelioconnect-washingtonstate",
  "West Virginia": "https://www.change.org/ameelioconnect-westvirginia",
  Wisconsin: "https://www.change.org/ameelioconnect-wisconsin",
  Wyoming: "https://www.change.org/ameelioconnect-wyoming",
  Federal: "https://www.change.org/ameelioconnect",
};
