import { TReviewItem } from "types";

export const REVIEWS: TReviewItem[] = [
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GhsCZepsoqWp81BKAmINHG_qId7qfAv9Bcxz7Xy=w96-h96-n-rw",
    author: "Claudia P",
    quote: "This app is a BLESSING! To be able to stay in touch with your loved ones and not worry about running out of stamps or envelopes...is amazing honestly. I've sent out a couple letters using this app & the person has received them without any problems. I was surprised that they actually sent out my letters! I love the tracker that way I know when it got to the facility. No complaints.",
    date: "June 23, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOHlmxg9LU5PY-Mc5rVsLLvZwsDvX_hEVzLG2Kmu_mDKLnmSQoQNhimb3rsSId-oZDa1VXP32ujJYWRYJw", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJyOMWyHpOsou93FlxhCW9cmBamADGBRb6t2nXer=w96-h96-n-rw-mo",
    author: "Mr. and Mrs. Done",
    quote: "Hands down the absolute best app for keeping in touch with incarcerated loved ones! Easy to use, totally free service that keeps you connected to the ones you cant be with. Even if you decide to make a purchase, which is not at all required to use the basic services, the options are definitely affordable and benefit everyone. I'm so thankful for this app!!",
    date: "June 27, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOHhg9hFpxpjHcDjyWhLIMJ6i-7Co8HdDOGERwh4wQbsb9F-PI6xSq7k9T3By2jxFxJRe1zAbHwqdku5wg", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJwFgdoYx3fG-jKfxpEZVzmk1yLb6s4y6vUfj7A0=w96-h96-n-rw-mo",
    author: "Janet James",
    quote: "This app is great if you have a loved on in jail, there is many fun activities sheet, coloring pages & more. I love using this app, I can just pull out my phone & write a letter or post card from my phone instead of writing it out by hand. I like this app",
    date: "June 9, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOF1Fk1iS1Zi7UYvvcVUFqJm_ZjS4JqCfqPhdMtUnZCO6cvjgQYQTnHZTy2h6V71gs-J1SAG8ABumLezJQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GiGkNxzxoBag-oK0-y-wn8aZHMT6uMq1VeJ5AW3nQ=w96-h96-n-rw",
    author: "Kelsey Range",
    quote: "I LOVE this app and when I was in Loudon Co jail, I told all my fellow inmates abt it. It was awesome seeing pple tht dont normally get mail start to get mail bc of the ameelio app. It truly makes a huge difference in your day behind bars when you get mail and it boosts your confidence knowing the world may keep on spinning without you but that there is at least someone tht notices your absence and misses you. I HIGHLY recommend this app for your incarcerated loved ones",
    date: "June 20, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOF2Xt8Yg4tkxWKjipdm3jHq4Xn2aAW0n8cLn0Li7Nams1tvdhurWK4EjXrQNgMQQzSB44LblAEFo5MhXQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJyQ6SLCd6kwNQGvaMvgH8W10T-hHXJiUiyMZsag=w96-h96-n-rw-mo",
    author: "Emmett Burns",
    quote: "This app is fantastic. It allows me to communicate with an incarcerated loved one so effectively and the customer support has been great the one time I needed it. This takes away my inability to get to buy stamps and mail things on my own. All of the new options for photo cards and other things are great too. I love this app so much, thank you",
    date: "June 6, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOG4ZrQ1uQvg8ci_3bNBTowMtpEZJPWUqa3oVqFJPlASOIVyL4gYk7r2IjA-beTOSHFxksosY5M7bUifyA", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GjVOIcLmxsjUf7A7bnstw5IiI7ECxlbDrOo8xL53w=w96-h96-n-rw",
    author: "Melissa Hotchkiss",
    quote: "This is so awesome im able to send pictures and a message on a post card to my friend who is in prison for free 3 or more times a week! This is amazing! I couldn't ask for anything better than this! I'm so grateful for this app! It really helps me & my family out a lot! Thank you Ameelio!",
    date: "June 27, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOFrFNqiWRmOjBNn6r-wCMr6a0oFpDsvlenVoEDRRMW2BcgCSp7Twh2PW9md6xFXybGv_5Rd6kxFohZ7Qw", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJzKld4yFZmwKVVLsTxKP5yurtlLW6lzXXNoZkAJ=w96-h96-n-rw-mo",
    author: "jack rap",
    quote: "I love the mission of this company. Its so easy just like sending an email. I just type the letter the do the rest print, postage, and send it off. I never even thought of sending games and so much more.",
    date: "June 13, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEvLHCv8EH9RbHFI2jHBfzcQyA39VLTyMib8ZVDM4hgtYCii2PULyySXBf2gQgLFeQsz_HUGlSCIDxy1w", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJwbaYEaE_gcKUSGAdCySjMTACcO3KqSzetTVkP2=w96-h96-n-rw-mo",
    author: "katheryne owen",
    quote: "Love this app! Easy to use and extremely helpful to get photo cards sent to your loved one. Most jails changed their letter policy and inmates can only get postcards but this app lets me send photos in the form of a postcard so its perfect!",
    date: "June 13, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOH_jqOmascYMAvjJByr094NSUlVAZvnX2sPJ2v7-Y7PO7KGI-QwNnjokqoncJXCdaELMTC3krOi6sfGaw", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GjQtUCHSVk6OixkJjZgsJInf23EZ5DajB8cMpBAYg=w96-h96-n-rw",
    author: "Robin Kennedy",
    quote: "Definitely can't complain or go wrong by using this app. Excellent app, highly suggest. Everything is fairly easy to use and self explanatory. Post cards looked excellent and just as described.",
    date: "June 18, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOFA4yVKy_mL6fgrkpEDqkfSFCjmWYJXk2BmdtJORnFoT6zuJRO-03_PpAph7_rhGeP71F9DOIjGyJt1Zw", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GiWA4zWxTm-nnnk07ZUYJiACeYJLUS5RIb4yRYfzQ=w96-h96-n-rw",
    author: "Jae Breezie",
    quote: "I absolutely love this app I as a former inmate know just how important mail is it's the best feeling when they slide that mail under your door lets you know people didn't forget about you this app makes it so much easier for me cuz I hate writing that's all I did when I was locked up so this is way better I appreciate you guys whomever made this god bless you and I being a former inmate as I said I would personally like too thank you on behalf of all the women at York Corrections here in CT❤️",
    date: "May 12, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOGUIvp2RrRMLedwNXmAqEJwmOI6bOZBvHRSF18vwlKSvEdVtNeiEipFB9mmH3hI7XSuDyaVSM2nNCsVkg", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14Gh6n3gnvLxaU_HmBBYu2MSaHDBxQDhwC0rcQTTtzLE=w96-h96-n-rw",
    author: "Lisa Bukowski",
    quote: "Ameelio is a wonderful app that is truly beneficial to anyone who has a LO incarcerated. You can send photo cards, letters, activity booklets, prison recipes and more for free. I wouldn't think to find and send recipes that he could actually make while incarcerated and they have recipe booklets all ready you just need to choose them, they have self help booklets, parenting from prison etc, things that are truly helpful to the people that recieve them and I'm so grateful to have found this app.",
    date: "June 11, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEmWVKyVBm_O7e9xh3zWf-OThr2C52mI6PnhZQrbOgm5gvNqRvxcDfg8gkebVDTAoXqQ9TAkIEtuBmejg", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GgbhjcDTlazK-jp2mBgwkuMcnOscGDzTeII8FX9Jw=w96-h96-n-rw",
    author: "Cherri Sweet",
    quote: "THIS APP!! TRULY AMAZING! They help you send photos, letters and so much more, piece of mind actually, to your loved 9nes. And families help others pay so lots are sent \"free\" to the user and incarcerated loved one! I love love love this app! Way better than flikshop .... Ty Ameelio",
    date: "May 10, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOGkjdZKyB00s4W4lRWH1QxjkjcdMzF0Oygq0KCaNetcsOGmByuCIcrc00XumnoclGilC_VlNJ8LArUgWg", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GhZDgq_1PdXNrnFSYXah9evizhw8nUbSvm1E0dFPRU=w96-h96-n-rw",
    author: "JK",
    quote: "This app helps me out tremendously, especially when your low on cash, I appreciate these guys so much for sending out free mail, even with a pic! I have recommended it to several people. THANK YALL AMEELIO",
    date: "June 23, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOE4F3kUZ5LrGA26bkFJCO-MOD2ayqDLkj6dGYCivNRKtY1jYb1T4uVs0Dogzqzwjygv3JlK20vcJLKxMQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14Gif6-Q3qS3dwF2FKrDFRN3DAhcnnhcOdTH329aLRw=w96-h96-n-rw",
    author: "Mary Ann Bensley",
    quote: "I love this app! My boyfriend is in prison and instead of worrying about stamps and envelopes I just have to use this app. I can send him pics and song lyrics and letters that he loves getting! Thank you so much ameelio!",
    date: "June 23, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEH3G7r4DSC23cU2XubW2bH0Seuj9nj_fJBCibUhh4i5KFnrqR3cf4o5QGwIotM3U4BmDvkx9PE1hzwew", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJxSzF9vEEn29-DNNX1icr7dKUa4czUm7ZXWfxv5=w96-h96-n-rw-mo",
    author: "jovannah bedford",
    quote: "This app is awesome! I've never experienced at a problem using the ameelio app! My loved one received all letters including photos! This is a awesome to keep in touch with your loved ones!",
    date: "May 26, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEbl1Nu3HUbvGHwAs8okgdsCe28X6V7hF1payV2Bz8EjQS8NuTmO8DMdN-h1BeAfy99BQMIgU3SNAAV4A", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJzW2lrD1KnUwbGEUd_NrBI5BXtmtzTKeYIEd34Z=w96-h96-n-rw-mo",
    author: "Sheena Love",
    quote: "It's amazing sending all my favorite inmates postcard with photos straight from my phone ! It helps me keep in touch and show them I care for free and easily ! Thank you so much for this app!!! I'd rate it 10 stars if I could !!!",
    date: "May 29, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOHpaV_EAOrTBducOe2e0LYJ1OaoAniwE5pJGjXbuNeVpiI0uvZh_LHUI2__aQlEMNAFkvrt45gS_7QyuQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14Gg3Qj3Z2LboqXyFlwXQBxEe4wtzcE3PYlaof3XGf7o=w96-h96-n-rw",
    author: "Jaclyn Marie",
    quote: "This app is heaven sent. It's incredible fir inmates and their loved ones. Making it easier to stay connected to your loved one. You Rock, Ameelio!!",
    date: "June 12, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEFyxyQcnKhqF8mM0WubXtGGBx1BbE4HjNiBqu7ehpQWtxChxIWf7P8cO5ZCgPzpEGWrUA7A1RHs9mRgA", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14Gh_q45E1QrW57XF1_T3aEjO0kKBpQZHpjHZE7NmQz0=w96-h96-n-rw",
    author: "Cassie Spanke",
    quote: "Extremely easy to use and soooo helpful. My loved one says the picture quality is amazing and loves receiving the post cards.",
    date: "June 30, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOE8Fdlpg0VOtpXS6nrCU-zQ0inFbzv6Lc5pggoC6dXB2X1oLDqHvnAgZdoNu2amix6NoSrzeVm3_i8ghQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GiMSnflHyqeTrPYtvxDFY1luV3VRy2kwlpwOCLGbYY=w96-h96-n-rw",
    author: "Billee Oxendine",
    quote: "I never leave reviews but I really do love Amelio. I send FREE postcards regularly and it helps me do something for my loved on on the spot in the moment and takes as little or as long as I want it to. It's great.",
    date: "May 31, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEDOwWG4PnfTpdJVAvXorfXzIqwzYUvDYt2zCX3KchtJH3KJpyZ0q9dtoLyMCycqj1e5W_w4XQ6LSD3tw", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GgJuzdX2TThujsLgtkLjUHDHXbGtWYsc5rAVuMwFw=w96-h96-n-rw",
    author: "EMILY MAE VILLALOBOS",
    quote: "Thank you. New restrictions to mail going to Utah DOC inmates have been awful. This is the only way for my husband to get a creative and colorful card or letter. Best app and best program ever. Thank you.",
    date: "May 7, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOFUO8g-lyXuoUP_O8A4Sa-3KsntlU0SM_cVD49RpFOnKrn-SCF0aLLZund6PFNRA4efsleNH_JLLutk4w", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJyTLYU-w_8JfSK-eqSDN5kgdnzXQVA6ztrFxyke=w96-h96-n-rw-mo",
    author: "Christen Waddle",
    quote: "I think this is absolutely outstanding to offer this type of service. This app surpassed my every possible expectation!",
    date: "June 11, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOFiVOE4SJFGVUmBmiDJcZ5xbNJCJsD6quwVBktn0CuFz2cY0GQypDt62L9F2m04TgWonFW7dz2w-i0e0A", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GjlDWltnohiSWtilyf_otxyp1bySeTnG0edBs0XLOE=w96-h96-n-rw",
    author: "Terri McGillivray",
    quote: "This is the most amazing app I have ever used. I am blessed to have a service like this when I can't afford to mail my son a letter plus they send pics with ur letter. Thank u Ameelio",
    date: "May 12, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEqETHoAuutmUDlqOCNfzhTcKDWHvDZZVT6JR4wwUAo_KZ-Ch0is9q3rmOV-ZWEFBOiZ3rVuK5RBAHHOA", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GhilEyiY7kCl05K_MKWifIk5GvAolfKHO8mg91L=w96-h96-n-rw",
    author: "Catie Brewer",
    quote: "I absolutely love this app. It helps me stay in contact with my family and friends who are in state and federal prison. This is very much a blessing to be able to do this.",
    date: "June 28, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEOCqgDf7MxStX2_GQikmMwX4jksj8fea4chfOXsHiv8LJSZXWX1XqiKtSeJ72l15snlUYXxA5-XVWtjQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GhFU0jiLilsMaT_IFGYnoX6VZ8RD6LMrVADyOazDQ=w96-h96-n-rw",
    author: "Randy Perez",
    quote: "My experience has been exceptional especially because now that things have changed out here with covid 19 and all it has been hard to come up with the necessary monies to keep in touch with our loved ones Thank you so much for making this possible",
    date: "June 20, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOHOHbirY2463FCTh8399XreUXTDFQEdsau7xZPVMeldUcogQv_sIbSD_yzPlwlsec5Oa36tNsPDgDxz9A", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14Ggr28b3Z12RXyZ_Hxzk-MHFlvcg9GY3r1bpxV9k=w96-h96-n-rw",
    author: "Debby Gage",
    quote: "My Son was told about this app by someone. Its amazing. He gets so excited to rec these post cards. And they are excellent quality. Extremely happy with Ameelio",
    date: "May 15, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEvpe6uIB-YOFMzxSbVfJ4rGbAGIRWw__bjP_xfOb5lcLiqQvyHw8CaKaRmF6wfghsEEQVttTWTfjcXHQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GgMFYNyprDPKv0GFZ_eVibsbwdfvn-34AERRNwF=w96-h96-n-rw",
    author: "Jessica Maddox",
    quote: "I love this app. My partner loves the cards I have sent her. They arrived on time and love that it's free to do",
    date: "June 5, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOHn-x-3mapPgdsBLQmZNWrgEjarJMDGy3JFFUIUsqjAprsGTPFEhoRTldeowWxnaUxWjQxAqmJ59Nu8uA", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJzVMfA5N1VouqgTmsgZx8aa3PEr3Zrm3_AuLs0B=w96-h96-n-rw-mo",
    author: "Wanda Lopez",
    quote: "I love this app. It's so appreciated. Thank you so much! My brother really enjoys seeing the family & our animals.",
    date: "May 24, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOHe3JajrjSTMYVzkmQ22ops8xwLax1J5YkcJZcSvYvE5OmAd8NeMAaqcrmusoxeO05J_TKAVsA_BTEobQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GjOpnk7zHDRKxpLGOzgqWx3vwSW21PdfcnctYsKeVQ=w96-h96-n-rw",
    author: "Andrea Seagrave",
    quote: "Amazing!! This organization helps keeps us in touch with our loved ones and the free picture postcards are an amazing gift for the family and the inmate. I wish I could give them more than 5 stars.",
    date: "June 27, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOFaVpklPrN7BlI4eEisDxfhEPblLXCaAc70K3JojIYtX_kD81KkB2cBH3w8Um-yV2VgFQC4MrYysMfaAQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GiL9xnmIxbRkGuewz50tV7rME9q9MrLrkzZ39OSzFY=w96-h96-n-rw",
    author: "Alisha Smith",
    quote: "It's easy to use and you can send it right through your phone. I have been very satisfied with the app. I highly recommend",
    date: "May 27, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOESHGfi6Z8RGWmDGWLBsRdoHn8wc7TGp510FtToTOw9_poHrwXTq0VeLxTGhkZbcEX3ZVV8XrrDq8URBQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJwPl2TJZ5j6-_1icYEmubemmBvZgCB-9Gnynz58=w96-h96-n-rw-mo",
    author: "Danielle Davidson",
    quote: "This app is AMAZING!!! The crew deserves EVERY donation and recognition they can get. Keep it up guys. There's a lot of people out there that needs something like this. YOU HAVE MY FULL SUPPORT!!",
    date: "June 11, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOGpO7uPjl5RUmqWohF5hm2lOfE-ifFUZbhQWhbZSHXKS0v-6nrt8Odj8u4771G9ImdT2kDCLzerO7gUKw", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GhrHa8ywXufbznv6cskBu_3-ddycUx-AlZQFLlXiA=w96-h96-n-rw",
    author: "Marci Rowan",
    quote: "Overall the best app I've ever downloaded. This is an app that is very important to so many. I appreciate it way more than I could ever express.",
    date: "June 13, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOFINUs0mMyN477Jmt2WOHviMC7KU8AbBMJvkanu7feCxxy0zIam7q9X1AbKdkaSmrfVdi0ReikO77ZrXQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GiUvYkyHrVp1eHbPYpnPpT5Z5ZhPsAjyBn6cnJY7g=w96-h96-n-rw",
    author: "Alley Spain",
    quote: "I love Ameelio and have used it to send quite a few postcards to my loved ones that are incarcerated. They even track the postcards all the way to the facility to ensure your person receives it. 5+++ stars!!",
    date: "May 16, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOHAcJkVIBYH_8CKL2t3e_ThHm4vtFjAzv6k9B-Lybc2QyKESJcFR08EeTX_CM6LR_tUIcr4pMGxbYehyg", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GgAuoAWtFq4V9zKBJ2w-B0Pg9eMpXg4vyL1GeZ9yZE=w96-h96-n-rw",
    author: "Alison Briggs",
    quote: "Thanks to this app Ive been able to reconnect with my loved one. Thank you",
    date: "May 30, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEYynBrkfXrzg1OLEV4-sBIdbe5zzfQsgPQSi5qphqIOF1wcskXjcFhtT7qoV5WYhI0SNybcWssSkseZg", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14Gi1EEMjNqoitWwiGKeZZVh1h7A2ePtfe6UUGMw7H0M=w96-h96-n-rw",
    author: "Heather Tate",
    quote: "LOVE THIS APP... THANK YOU FOR YOUR KINDNESS IN HELPING US CONNECT WITH OUR LOVED ONES DURING THE COVID... I SHARE IT WITH EVERYONE... THIS APP IS GENIUS 👌👍",
    date: "May 12, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOF4saZBlzh89-rHpzGF6tGTXzZAMt9q3RHhuhzOQywwoDvMf4wcyVJiPO-CuMjjuim5imknfTypeWHJBA", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJwMfrduA5De_a3JmdOaItOc9Qtzcs5D3QVrjCeP=w96-h96-n-rw-mo",
    author: "Jahu J",
    quote: "This is the BESSSSST app ever they are very timely and these cards have truly blessed my loved one and has kept us connected through this hard separation. Thank you Ammelio staff for being passionate and caring about families staying connected!!! God bless you all!",
    date: "July 7, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOF3oV_3cdfEl1sKRDIF0WF1eHaGQOU90ZHK1nK6p6XkLGdwIOzqnJdukX8eZnUyr1eo-no3frw8gycbLw", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GiIqUpLJf8VpINmHe9ydtyQhpVWwyIk6z_5kjXW1hE=w96-h96-n-rw",
    author: "siara hafner",
    quote: "My boyfriend showed me to this App and he is locked up. Sometimes you just hit hard times and this gives you that little extra help to stay connected to your loved one. They give you so many options to do different things it is just amazing. I'm still figuring it all out, I love this App so much and everything it stands for. Such a blessing, thank you!",
    date: "April 28, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOFZSnCL25z_O90JxXPWc4ABykA1euFSE321jFWLVZzYf1fIe1rtEqh8ighwBiGaHLO7_vck3t3XmdJiUw", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GhWPRzBVroJkjWAJEr2b3Il1YZ2Q61cqD6Cl5pbCg=w96-h96-n-rw",
    author: "Kristy Meekins",
    quote: "This has allowed ya to keep a strong bond between my grandkids and their parents that might have been lost. It gives hope to loved ones and helps them stay strong. This is the best thing ever.. Thank you so much for providing this to the ones who are unable to afford it. It is and continues to be a huge blessing.",
    date: "March 3, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOGdWoH2L4ddJdPP8VGXnPHQQ0Th5g0EPerb8A6rlPt6SXHuIPimzqxw05Im3DMOJP0CJaGLccJuVbTzkQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJwkZpIwBYMq0odh-eW7EXl8EIFauNH09D_o43cs=w96-h96-n-rw-mo",
    author: "Darcey McConnell",
    quote: "So appreciative to the creators of this app. It is a great way to make contact, keep in touch, and include our family member, in our recent gatherings and up-to-date news and events. Thank you very very much!!",
    date: "March 14, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEJc8aHL8GIOPYX5kozaXoeUdY_TMCZWBNrl2SRC-IlJbihN8txwEzJbiI9ZNq6gnEC7SLU_leA-EtZrA", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GiLxsedlYK0MOUR4nrFTiVZp-m-uRpp9BiBYYFbnw=w96-h96-n-rw",
    author: "John Graves",
    quote: "This is truly an awesome website able to communicate with my family and friends sending photos sending gifts just able to share with them the small things that's on this application thank you so much for giving us an opportunity to share be blessed and may God continue to smile upon the developers of this application",
    date: "March 4, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOGWN3kDopLkNRB7IObz4e9o23wA99lVhf0IlzFfBVtJbg2afXmafg9sq1V_BuAVFwOJjb4iwzuZ3yt6Cw", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GjPBS4uOuYzOi8CFaOTHIo4zhXLArzM83HaYOoKxw=w96-h96-n-rw",
    author: "Carlos Sanchez",
    quote: "This is a great experience to get in touch with my brother and I'm sure for other people to get in touch with their loved ones it's very simple and great to share with other family members thank you very much for whoever created this",
    date: "February 22, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOE4yJGeO_rDwrylSqSQ7RSbuWkkduj_gx0pl1OS6oBBgvOk_XjYuC0_1ZnuEGExxDbfre5-qqVTHD-d2Q", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GgalbobQHdLPcya7Ci-pJct3evPJ6-5dMDkzT6T=w96-h96-n-rw",
    author: "Hilarie Matthews",
    quote: "I love ameelio so happy I can write my boyfriend letters and send pictures for free it definitely helps alot since phone calls and jpays can add up quick. Im very grateful for ameelio ❤",
    date: "June 6, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOE20lAejI7RhaEOCM1kgMQaJlDAZnzK6IDSy9B8-m6XkFsbsFFTd9wpywLQVmhNbg0iTr3812PWVE-APQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GjREJpEoSQDjvB-bWCVWNRHrT-6kJ3Sce3xkYn4XVw=w96-h96-n-rw",
    author: "Melissa C",
    quote: "LOVE THIS APP! Makes it so easy to send pics and postcards to my friend in jail. He loves it too. I'd give it 10 stars if I could..Thank you Ameelio!!",
    date: "February 13, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEGzkcdaMxEbdRyQxbullNuRaKsLT5Pryxc-uQb_C5OYH6HStcgFmunrL0IewKkCS5BVuPT9268MO0sHA", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GjddbDu7-8y4wiuG5-BQeved-BA9UvePCR1jXIQsA=w96-h96-n-rw",
    author: "Ruby Garcia",
    quote: "The kindest act you can give to an inmate and their family, the gift of communication, and that's exactly what this kind group of people do, with nothing in return expected. Amazing app. Thank you to all who make this possible. God bless",
    date: "February 26, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOF7Lu_V7VmMEpuFTWlHP2gpyHk2T9CyRw5VVR8AlUstcrjaSPiveufTCnbSw1y6mzTalml3urMYigIHxQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14GgTSoqw0VBwMK2ANJCT0fSe7hrc59sNtc6Q0Gfw2g=w96-h96-n-rw",
    author: "Ashley Shaw",
    quote: "I can't say enough about how wonderful this app is to help inmates and their families communicate!",
    date: "April 12, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOFRSB57g3jmd3oPqjNWLna7yD7gfUUkfIbwHLQ-4LF0qTrlk8a7E8K6P5m1RPlTh9YkTJ23yZuaJl7ZXw", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14Gg4YwWb0e0ucPnWR77mqnU99II4uIai7SKxUkjX=w96-h96-n-rw",
    author: "Julie Gammon",
    quote: "Ameelio has been a god send. I miss my man and i want him to know he's important and not forgotten. Ameelio has been so much help with that.",
    date: "July 4, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOHURsLiNySF05DEqDLKtZDKxH1roek51bV3nnRZA7I9m0KD_JDa89GlAzTVFN0xOs1QcfYzeIXQbUouaA", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14Gjz_V53RpP50sX1yLwJmhRtc495K_77u2pLY1-myw=w96-h96-n-rw",
    author: "Ruthie Bauman",
    quote: "I am sooo thankful for this app. To be able to communicate with my son means everything to me Sincerely one happy momma",
    date: "March 2, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOFPCCzL5NULxvFaIfUOx50Mu1-uTzh7bpbBm6uBjlN7wmfg32g6t1IcAAf5mj888i8zQsrPoFIo6Ada-A", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14Gj_5O2iXfZ5Odts0TKQPUrtpPVR2-9qymSxgOSi=w96-h96-n-rw",
    author: "Pam Childress",
    quote: "Thank you for helping bring a smile to my son's face. He's enjoyed receiving these. No problems for me",
    date: "April 10, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOF1WkmRPfhfj6oL9n0TSO39SuHN1ollbcmp1jv9DUr6_XWO-mTc1es47HK_kyyiLgiARAef5NqC3jFptA", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJxd5b_XO5R5Njc0mPbwwVd1ZLOcDjVSi5sU1--d=w96-h96-n-rw-mo",
    author: "Yolanda Warner",
    quote: "Before Ameelio, I would write to my son, but for lack of stamps, envelopes, missing the mailman, etc.. the letters end up in my folder...son never received them. Now, i think of my son, at 3am, i send him a letter, via Ameelio! Thanks for this great program.",
    date: "February 16, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOGwhUdDeXibzQtCbxkIWocPf3cKbANX8jkdzJJuI5Dp4sro1lJJgxjUie5lIffeOV0gHzAr_WH0zzgC4A", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJwVgJIQq4iCxqrLiomwKti-cCSgDk2T7ScXFfM9=w96-h96-n-rw-mo",
    author: "Heidi Brickman",
    quote: "Best way to send my love all the pictures, and notes I think about during the day, I love being able to hop on here and just send him a quick card letting him know I'm thinking of him!! Thank you Ameelio",
    date: "June 21, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEWh5OFuSEDSTOPJjR7MxLlhEo77c5AnzqxDO4Y9rAo1pH-D5ZDGzmV0xu1Qia_1_T37DaZEXgI5PBJYQ", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a/AATXAJwG7TlUu_WSrDiUomt4Y2sWUgVrYxMV3AS8DHlr=w96-h96-n-rw-mo",
    author: "KJ Beck-Smith",
    quote: "I found this app from a friend. It is amazing to send my lo a letter & picture card. He looks forward to mail call & tells all his friends about this non profit service. Them guys now are receiving letters too. Thank you so much for offering this service so I can stay in contact with my lo. Even my friend is writing to her father again! Bless you.",
    date: "February 27, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOEYc-V6CUEavG3WCbLPU1oXfPdvMZVUholLeOSefjraM848oKg_41F6GL3l4tYKJpCI_FBLD9zNc0a2gA", 
  },
  {
    imageSrc: "https://play-lh.googleusercontent.com/a-/AOh14Gg9kBYvDSbymZ8yWjLy_0PIwyi8bIPCdOHGadn9dg=w96-h96-n-rw",
    author: "Amber DC",
    quote: "•IF YOU HAVE INCARCERATED FAMILY• •NO BULLSH*T THIS APP IS WORTH IT• •HANDS DOWN THE BEST APP EVER• And I mean best app I have ever used in my entire life! I am the wife of a Husband in prison with over 100 months in and 48 months until he is home! I recommend this app to everyone I know with incarcerated loved ones. It is the easiest app ever created! You will not be disappointed!",
    date: "May 2, 2021",
    link: "https://play.google.com/store/apps/details?id=com.ameelio.letters_mobile&hl=en_US&gl=US&reviewId=gp%3AAOqpTOFTk1vHJJNUwInIanKWnokpkm7lcRzd5I6y267TmPxhHm5LDxoczD10KgNKlP6iZjOGt1V_xnje_LJrOg", 
  },
];